import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '../api/axios';

export const generateBreakageVoucherPDF = async (idOrData) => {
  try {
    let header = {};
    let items = [];

    if (typeof idOrData === 'object' && idOrData !== null) {
      header = idOrData.header || idOrData;
      items = idOrData.items || [];
    } else if (idOrData) {
      const res = await api.get(`/ward-issue/${idOrData}/print`);
      header = res.data?.header || {};
      items = res.data?.items || [];
    }

    const doc = new jsPDF('portrait', 'pt', 'a4');
    const facility = header.FacilityName || 'FACILITY';
    const location = `${header.DistrictName || 'DISTRICT'}, ${header.StateName || 'STATE'}`;

    // --- Header ---
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(facility.toUpperCase(), doc.internal.pageSize.getWidth() / 2, 40, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(location.toUpperCase(), doc.internal.pageSize.getWidth() / 2, 55, { align: 'center' });

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('BREAKAGE VOUCHER', doc.internal.pageSize.getWidth() / 2, 75, { align: 'center' });

    doc.setLineWidth(0.5);
    doc.line(40, 85, doc.internal.pageSize.getWidth() - 40, 85);

    // --- Meta Info ---
    doc.setFontSize(9);
    const issueDate = header.IssueDate ? new Date(header.IssueDate).toLocaleDateString('en-GB') : '—';
    const voucherNo = header.IssueNo || '—';
    const remarks = header.Remarks || '—';

    doc.text(`Issue Date : ${issueDate}`, 40, 103);
    doc.text(`Voucher No : ${voucherNo}`, 320, 103);
    doc.text(`Remarks : ${remarks}`, 40, 119);

    // --- Table Data ---
    const tableBody = items.map((item, idx) => {
      const batchesText = (item.batches || []).map(b => 
        `Batch: ${b.BatchNo || '—'} | Qty: ${b.IssueQty || 0} | Exp: ${b.ExpDate ? new Date(b.ExpDate).toLocaleDateString('en-GB') : '—'} | Loc: ${b.StockLocation || '—'}`
      ).join('\n');

      return [
        idx + 1,
        `${item.ItemCode || ''} - ${item.ItemName || ''}\nStrength: ${item.Strength || '—'} | SKU: ${item.SKU || '—'}`,
        item.CurrentStock !== undefined && item.CurrentStock !== null ? Number(item.CurrentStock).toLocaleString('en-IN') : '0',
        item.IssueQty || '0',
        batchesText || '—'
      ];
    });

    autoTable(doc, {
      startY: 135,
      head: [['Sl. No.', 'Item Details', 'Facility Stock', 'Breakage Qty', 'Batches Details']],
      body: tableBody,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 4, lineColor: [200, 200, 200], lineWidth: 0.5 },
      headStyles: { fillColor: [30, 62, 44], textColor: [255, 255, 255], fontStyle: 'bold' },
      columnStyles: {
        0: { halign: 'center', cellWidth: 35 },
        1: { cellWidth: 150 },
        2: { halign: 'right', cellWidth: 70 },
        3: { halign: 'right', cellWidth: 70 }
      }
    });

    const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : 160;

    // --- Signature ---
    const sigY = finalY + 50;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.line(60, sigY, 200, sigY);
    doc.text('Generated By', 130, sigY + 14, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('store keeper', 130, sigY + 26, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.line(380, sigY, 520, sigY);
    doc.text('Verified By', 450, sigY + 14, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('superintendent / MOIC', 450, sigY + 26, { align: 'center' });

    const fileName = `Breakage_Voucher_${(voucherNo || 'Doc').replace(/[^a-zA-Z0-9.\-_]/g, '_')}.pdf`;
    doc.save(fileName);
  } catch (err) {
    console.error('Error generating Breakage Voucher PDF:', err);
    throw err;
  }
};
